const state={transactions:[{name:'Makanan',note:'Belanja sayur',amount:35000,time:'08:12',icon:'🍜'},{name:'Belanja',note:'Keperluan rumah',amount:120000,time:'12:30',icon:'🛒'},{name:'Transport',note:'Ojek online',amount:25000,time:'17:45',icon:'🚗'}],goals:[['🚗','Target Mobil',20000000,8500000],['🌴','Liburan Keluarga',5000000,4100000],['🛡️','Dana Darurat',10000000,2750000],['🏠','Renovasi Rumah',15000000,3200000]],accounts:[['💵','Dompet','Rp 350.000'],['🏦','Bank BCA','Rp 2.150.000'],['🟣','E-Wallet (OVO)','Rp 745.000'],['🏦','Tabungan','Rp 5.000.000']]};
const fmt=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
function render(){todayList.innerHTML=state.transactions.map(t=>`<div class="tx"><div class="tx-icon">${t.icon}</div><div class="tx-main"><b>${t.name}</b><small>${t.note} · ${t.time}</small></div><div class="tx-amount">− ${fmt(t.amount)}</div></div>`).join('');goals.innerHTML=state.goals.map(g=>{let p=Math.round(g[3]/g[2]*100);return `<div class="goal"><div class="goal-top"><div class="goal-icon">${g[0]}</div><div class="goal-title"><b>${g[1]}</b><small>${fmt(g[3])} / ${fmt(g[2])}</small></div><div class="goal-value">${p}%</div></div><div class="progress"><i style="width:${p}%"></i></div><div class="goal-foot"><span>Terkumpul ${fmt(g[3])}</span><span>Target ${fmt(g[2])}</span></div></div>`}).join('');accountsList.innerHTML=state.accounts.map(a=>`<div class="account"><div class="account-icon">${a[0]}</div><div class="account-main"><b>${a[1]}</b><small>Saldo saat ini</small></div><strong>${a[2]}</strong></div>`).join('');}
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===id));window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>showPage(n.dataset.page));
const modal=document.getElementById('modal');addBtn.onclick=()=>{modal.classList.remove('hidden');date.value=new Date().toISOString().slice(0,10)};closeModal.onclick=()=>modal.classList.add('hidden');modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};document.querySelectorAll('.type-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.type-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
saveTx.onclick=()=>{const n=Number(amount.value.replace(/\D/g,''));if(!n)return alert('Masukkan nominal terlebih dahulu.');const cat=category.value;const icons={Makanan:'🍜',Belanja:'🛒',Transport:'🚗',Rumah:'🏠',Kesehatan:'❤️',Pendidikan:'🎓',Hiburan:'🎮',Lainnya:'•••'};state.transactions.unshift({name:cat,note:note.value||'Transaksi baru',amount:n,time:new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}),icon:icons[cat]||'💳'});render();modal.classList.add('hidden');amount.value='';note.value='';showPage('home')};
toggleBalance.onclick=()=>{const b=document.getElementById('balance');b.textContent=b.textContent==='••••••'?'Rp 9.245.000':'••••••'};
render();
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
